apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microservices-app
  template:
    metadata:
      labels:
        app: microservices-app
    spec:
      containers:
        - name: microservices-app
          image: yourusername/microservices-app:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: microservices-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: microservices-app
